// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/m/[id].tsx";
import * as $3 from "./routes/ws/[id].ts";
import * as $$0 from "./islands/Connection.tsx";
import * as $$1 from "./islands/Game.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/m/[id].tsx": $2,
    "./routes/ws/[id].ts": $3,
  },
  islands: {
    "./islands/Connection.tsx": $$0,
    "./islands/Game.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
